spring.application.name=property-rental-backend

spring.datasource.url=jdbc:mysql://localhost:3306/property_db 
spring.datasource.username=root
spring.datasource.password=Aditya@9022

spring.jpa.show-sql=true


jwt.secret=propertyrentalprojectsecretkeypropertyrentalprojectsecretkey
jwt.expiration=86400000